/*
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import java.io.*;

class EvenFibonacci{
  
  
  
  public static void main(String args[]){
    
    long sum=0,fibo=0,x=0,y=1,limit=4000000;
    
    while(fibo<limit){
    
      fibo=x+y;
      x=y;
      y=fibo;
      
      System.out.println("Next fibonacci number : "+fibo );
      
      if(fibo%2==0 && fibo<=limit){
        sum+=fibo;
      }
    
    }
  System.out.println("Sum: "+sum);
}
  
}